{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNkTDxMwkqb7YLNf1pokAbm",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/titanioco/Proyecto-Final-DB/blob/main/Proyecto_final.sql\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "0OyEY0Ea_wvO"
      },
      "outputs": [],
      "source": [
        "-- Tabla de Entidades (Entidad contratante), normalizada a partir de ID_ENTIDAD y nombre de entidad.\n",
        "CREATE TABLE entidad (\n",
        "    id_entidad      INT PRIMARY KEY AUTO_INCREMENT,\n",
        "    nombre_entidad  VARCHAR(255) NOT NULL,\n",
        "    caracter_entidad VARCHAR(20),            -- Ej: 'Pública', 'Privada', 'Mixta'\n",
        "    -- Otros posibles campos de entidad (opcionalmente contactos generales, etc.)\n",
        "    INDEX idx_nombre_entidad (nombre_entidad)\n",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n",
        "\n",
        "-- Tabla principal Base Maestra de proyectos (datos consolidados y aprobados de cada proyecto)\n",
        "CREATE TABLE base_maestra (\n",
        "    id_cid              INT PRIMARY KEY AUTO_INCREMENT,   -- Código interno único de proyecto (CID)\n",
        "    id_entidad          INT NOT NULL,\n",
        "    id_quipu            VARCHAR(50),    -- Código QUIPU (se llenará al aprobar contrato)\n",
        "    id_hermes           VARCHAR(50),    -- Código HERMES (se llenará al aprobar contrato)\n",
        "    -- Campos de identificación y generales (no duplicados en otras tablas):\n",
        "    interfic            TINYINT(1),     -- Indicador InterFic (0/1)\n",
        "    ati                 TINYINT(1),     -- Indicador ATI (0/1)\n",
        "    facultad_lider      VARCHAR(100),   -- Nombre de la facultad líder\n",
        "    objeto              TEXT,           -- Objeto/Descripción del proyecto\n",
        "    saber_cid           VARCHAR(100),   -- Área de saber CID (categoría de conocimiento)\n",
        "    modalidad_extension VARCHAR(100),   -- Modalidad de Extensión (ej. Educación continua, Consultoría, etc.)\n",
        "    valor_contrato_fce  DECIMAL(15,2),  -- Valor del contrato asignado a FCE (final aprobado)\n",
        "    valor_contrato_marco_final DECIMAL(15,2),  -- Valor final del Contrato Marco (aprobado tras modificaciones)\n",
        "    otras_transferencias_est DECIMAL(15,2),    -- Otras transferencias (estimado) - mantenido en base\n",
        "    transferencia_fce_est   DECIMAL(15,2),     -- Transferencia FCE (estimado) - mantenido en base\n",
        "    director            VARCHAR(100),   -- Nombre del director del proyecto\n",
        "    tipo_direccion      VARCHAR(50),    -- Tipo de dirección (ej. Interna/Externa)\n",
        "    -- Campos de estado de Propuesta (consolidado en base):\n",
        "    estado_propuesta    VARCHAR(100),   -- Estado de la propuesta (ej. \"Adjudicada\", \"Presentada y no adjudicada\", etc.)\n",
        "    fecha_presentacion_cf_av DATE,      -- Fecha presentación en Consejo de Facultad (acuerdo de voluntades)\n",
        "    acta_presentacion_cf_av   VARCHAR(50),    -- Acta de presentación en Consejo de Facultad (acuerdo de voluntades)\n",
        "    estado_firma        VARCHAR(50),    -- Estado de firma del contrato (ej. \"Firmado\", \"Pendiente\")\n",
        "    id_acuerdo_voluntades VARCHAR(50),  -- ID del Acuerdo de Voluntades\n",
        "    fecha_firma_acuerdo_vol DATE,       -- Fecha de firma del Acuerdo de Voluntades\n",
        "    fecha_firma_contrato DATE,          -- Fecha de firma del contrato marco\n",
        "    id_resolucion_inicio   VARCHAR(50), -- Número/ID de la resolución de inicio de ejecución\n",
        "    fecha_inicio        DATE,           -- Fecha de inicio de ejecución (real)\n",
        "    fecha_finalizacion_pror DATE,       -- Fecha de finalización con prórrogas (real, final)\n",
        "    modificaciones      INT,            -- Cantidad de modificaciones al contrato\n",
        "    tipo_modificaciones VARCHAR(255),   -- Tipo(s) de modificaciones realizadas\n",
        "    valor_direccion     DECIMAL(15,2),  -- Valor por dirección (honorarios del director)\n",
        "    tipo_vinculacion_director VARCHAR(50), -- Tipo de vinculación del director (ej. planta, contratista)\n",
        "    presupuesto_comprometido DECIMAL(15,2), -- Presupuesto comprometido (valor total comprometido)\n",
        "    porc_presupuesto_comprometido DECIMAL(7,2), -- % del presupuesto comprometido\n",
        "    valor_ejecutado     DECIMAL(15,2),  -- Valor ejecutado (gasto realizado)\n",
        "    porc_facturacion    DECIMAL(7,2),   -- % Facturación alcanzada (porcentaje facturado vs comprometido)\n",
        "    facturacion         DECIMAL(15,2),  -- Total facturado (ingresos facturados)\n",
        "    porc_ingresos       DECIMAL(7,2),   -- % Ingresos recibidos vs comprometido\n",
        "    ingresos            DECIMAL(15,2),  -- Total ingresado/pagado\n",
        "    estado_ejecucion    VARCHAR(50),    -- Estado de ejecución (ej. \"En ejecución\", \"Finalizado\")\n",
        "    excedentes          DECIMAL(15,2),  -- Excedentes (fondos no ejecutados, devueltos)\n",
        "    porc_participacion_fce DECIMAL(7,2), -- % Participación FCE (porcentaje de participación financiera FCE)\n",
        "    fecha_liquidacion   DATE,           -- Fecha de inicio de liquidación\n",
        "    fase_liquidacion    VARCHAR(50),    -- Fase de liquidación (ej. \"En liquidación\", \"Liquidado\")\n",
        "    -- Clave foránea a Entidad\n",
        "    FOREIGN KEY (id_entidad) REFERENCES entidad(id_entidad)\n",
        "        ON UPDATE CASCADE ON DELETE RESTRICT,\n",
        "    -- Índices para consultas rápidas:\n",
        "    UNIQUE KEY uq_quipu (id_quipu),\n",
        "    UNIQUE KEY uq_hermes (id_hermes),\n",
        "    INDEX idx_entidad (id_entidad),\n",
        "    INDEX idx_estado_prop (estado_propuesta),\n",
        "    INDEX idx_estado_ejec (estado_ejecucion)\n",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n",
        "\n",
        "-- Tabla de Propuestas (etapa de propuesta/cotización).\n",
        "-- Incluye campos específicos de la etapa de propuestas que no están en Base Maestra.\n",
        "CREATE TABLE propuestas (\n",
        "    id_cid              INT PRIMARY KEY,   -- usa el mismo ID de Base Maestra (1 a 1)\n",
        "    tipologia           VARCHAR(50),       -- Tipología de propuesta (ej. Propuesta, Cotización, Invitación)\n",
        "    origen_proceso      VARCHAR(100),      -- Origen del proceso (ej. Concurso de méritos, Invitación directa, etc.)\n",
        "    num_proceso         VARCHAR(50),       -- Número de proceso (identificador del proceso licitatorio)\n",
        "    caracter_entidad    VARCHAR(20),       -- Carácter de la entidad (Pública/Privada/Mixta) - redundante con entidad, pero se conserva informativamente\n",
        "    otras_entidades     VARCHAR(255),      -- Otras entidades participantes (si las hay, listado)\n",
        "    modalidad_contratacion VARCHAR(100),   -- Modalidad de contratación (ej. Directa, Concurso abierto, etc.)\n",
        "    valor_cotizacion    DECIMAL(15,2),     -- Valor de la cotización/propuesta (estimación inicial)\n",
        "    valor_contrato_marco DECIMAL(15,2),    -- Valor del Contrato Marco propuesto (inicial)\n",
        "    valor_contrato_otra_fac DECIMAL(15,2), -- Valor del contrato aportado por otra facultad (si aplica)\n",
        "    valor_proyecto_fce  DECIMAL(15,2),     -- Valor del proyecto para FCE (estimado inicial)\n",
        "    tiempo_ejecucion_estimado VARCHAR(50), -- Tiempo de ejecución estimado (ej. \"3 meses\", \"1 año\")\n",
        "    fecha_recepcion     DATE,              -- Fecha de recepción de la invitación/solicitud\n",
        "    fecha_entrega       DATE,              -- Fecha de entrega de la propuesta\n",
        "    -- Estado de la propuesta se lleva en Base Maestra (estado_propuesta).\n",
        "    observaciones       TEXT,              -- Comentarios/observaciones de la etapa de propuesta\n",
        "    contacto_entidad    VARCHAR(255),      -- Datos de contacto en la entidad (persona, teléfono/email)\n",
        "    id_autorizacion_dneipi VARCHAR(50),    -- ID de autorización DNEIPI (si aplica)\n",
        "    fecha_presentacion_cf_prop DATE,       -- Fecha presentación Consejo de Facultad (propuestas/cotización)\n",
        "    acta_presentacion_cf_prop VARCHAR(50), -- Acta presentación Consejo de Facultad (propuestas/cotización)\n",
        "    -- (Campos de acuerdo de voluntades se registran en Base Maestra una vez aprobado)\n",
        "    -- Clave foránea a Base Maestra:\n",
        "    FOREIGN KEY (id_cid) REFERENCES base_maestra(id_cid)\n",
        "        ON UPDATE CASCADE ON DELETE CASCADE\n",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n",
        "\n",
        "-- Tabla de Ejecucion (etapa de ejecución del proyecto).\n",
        "-- Incluye campos específicos de ejecución (seguimiento contractual y financiero).\n",
        "CREATE TABLE ejecucion (\n",
        "    id_cid             INT PRIMARY KEY,    -- Misma PK que Base Maestra (1 a 1 con proyecto)\n",
        "    tipo_proyecto      VARCHAR(50),        -- Tipo de proyecto (ej. Extensión, Investigación, etc.)\n",
        "    vigencia_proyecto  VARCHAR(10),        -- Vigencia (año) del proyecto\n",
        "    contrato           VARCHAR(100),       -- Número/identificación del contrato suscrito\n",
        "    -- (Entidad, Director se obtienen de Base Maestra)\n",
        "    valor_adicion      DECIMAL(15,2),      -- Valor de adición al proyecto (montos adicionales aprobados)\n",
        "    num_vinculacion    VARCHAR(50),        -- Nº de vinculación del director (contrato del director, si aplica)\n",
        "    -- (Valor dirección está en Base Maestra)\n",
        "    -- (Acuerdo de voluntades: fecha e ID se registraron en Base Maestra)\n",
        "    fecha_inicio_ejecucion DATE,           -- Fecha de inicio de ejecución (planificada/real inicial)\n",
        "    fecha_fin_ejecucion    DATE,           -- Fecha de finalización (planificada originalmente, sin prórrogas)\n",
        "    -- (Fecha final con prórrogas está en Base Maestra)\n",
        "    -- (Modificaciones están en Base Maestra como totales)\n",
        "    fecha_fin_dir       DATE,              -- FECHA FINALIZACIÓN ORDEN DEL DIRECTOR (si aplica, p.ej. finalización según dirección)\n",
        "    -- Seguimiento de pólizas: podrían ser una tabla aparte; aquí podemos guardar indicadores si se requiere\n",
        "    poliza6            VARCHAR(50),        -- (Poliza tipo 6 - detalle o estado, en caso de manejar individualmente)\n",
        "    poliza7            VARCHAR(50),        -- (Poliza tipo 7)\n",
        "    poliza8            VARCHAR(50),        -- (Poliza tipo 8)\n",
        "    poliza9            VARCHAR(50),        -- (Poliza tipo 9)\n",
        "    gestor             VARCHAR(100),       -- Gestor del proyecto (persona encargada en ejecución)\n",
        "    responsable_ejecucion VARCHAR(100),    -- Responsable en ejecución (ej. coordinador AGEP)\n",
        "    obs_ejecucion      TEXT,               -- Observaciones de la ejecución\n",
        "    -- Seguimiento de facturación y pagos (resumen actual):\n",
        "    pago_num           INT,                -- Número de pago (secuencia del último pago realizado, si se lleva control)\n",
        "    factura_no         VARCHAR(50),        -- Factura electrónica No. (última factura emitida)\n",
        "    fecha_factura      DATE,               -- Fecha de emisión de la factura\n",
        "    fecha_vencimiento  DATE,               -- Fecha de vencimiento de la factura\n",
        "    dias_para_vencer   INT,                -- Días faltantes para vencer (si la factura está pendiente)\n",
        "    alerta_vencimiento VARCHAR(20),        -- Alerta de vencimiento (ej. 'Por vencer', 'Vencida')\n",
        "    valor_factura      DECIMAL(15,2),      -- Valor de la factura emitida\n",
        "    condiciones_pago   VARCHAR(100),       -- Condiciones y % de pago (descripción de condiciones de pago)\n",
        "    estado_factura     VARCHAR(50),        -- Estado de la factura (ej. 'Pagada', 'Pendiente')\n",
        "    comprobante_ingreso VARCHAR(50),       -- Nº Comprobante de ingreso (cuando se recibe el pago)\n",
        "    estado_pago_proy   VARCHAR(50),        -- Estado de pago en el proyecto (ej. 'Al día', 'Mora')\n",
        "    total_contratos    INT,                -- Número de contratos (subcontratos) en el proyecto, si aplica\n",
        "    contratos_pend_pago INT,               -- Nº de contratos pendientes de pago\n",
        "    valor_comprometido DECIMAL(15,2),      -- Valor comprometido (debería coincidir con presupuesto_comprometido en Base Maestra)\n",
        "    valor_pagado       DECIMAL(15,2),      -- Valor pagado hasta la fecha\n",
        "    saldo_por_ejecutar DECIMAL(15,2),      -- Saldo por ejecutar (fondos pendientes por ejecutar)\n",
        "    -- (Total facturado, %facturación, total pagado, %ingresos se reflejan en Base Maestra)\n",
        "    FOREIGN KEY (id_cid) REFERENCES base_maestra(id_cid)\n",
        "        ON UPDATE CASCADE ON DELETE CASCADE\n",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n",
        "\n",
        "-- Tabla de Liquidacion (etapa de liquidación del proyecto).\n",
        "-- Incluye campos específicos del cierre y liquidación contractual.\n",
        "CREATE TABLE liquidacion (\n",
        "    id_cid            INT PRIMARY KEY,    -- Misma PK de proyecto (1 a 1 con Base Maestra)\n",
        "    tipo_proyecto     VARCHAR(50),        -- Tipo de proyecto (redundante a ejecucion, incluido para referencia rápida)\n",
        "    vigencia_proyecto VARCHAR(10),        -- Vigencia del proyecto (año)\n",
        "    contrato          VARCHAR(100),       -- Nº de contrato (reiterado para referencia)\n",
        "    fecha_firma_contrato DATE,            -- Fecha de firma del contrato (si no se obtuvo antes)\n",
        "    -- (Entidad, Director obtenibles desde Base Maestra)\n",
        "    valor_contrato_total DECIMAL(15,2),   -- Valor total del contrato (incluyendo todas las partes)\n",
        "    valor_ejecucion_fce  DECIMAL(15,2),   -- Valor de ejecución FCE (lo efectivamente ejecutado por FCE)\n",
        "    fecha_inicio       DATE,              -- Fecha de inicio del contrato (ya en Base Maestra, pero se incluye si necesario)\n",
        "    fecha_fin_ejecucion DATE,             -- Fecha de fin de ejecución (sin prórrogas)\n",
        "    -- (Fecha fin con prórrogas en Base Maestra)\n",
        "    meses_ejecucion_pror INT,            -- Meses de ejecución con prórrogas\n",
        "    -- (Transferencias estimadas se registraron en Base Maestra; las reales se desglosan abajo en detalle)\n",
        "    supervisor_email   VARCHAR(100),      -- Correo electrónico del supervisor por parte de la entidad\n",
        "    estado_en_hermes   VARCHAR(50),       -- Estado del proyecto en HERMES (ej. 'Liquidado', 'Activo')\n",
        "    -- Gastos por categoría: se normalizarán en tabla aparte (liquidacion_gasto)\n",
        "    -- A continuación, campos de cierre y estados finales:\n",
        "    estado_liquidacion VARCHAR(50),       -- Estado de la liquidación (ej. 'Liquidado', 'En liquidación')\n",
        "    res_liquidacion_no VARCHAR(50),       -- Resolución de Liquidación No.\n",
        "    pdf_res_liquidacion VARCHAR(255),     -- Ruta o referencia al PDF de la Resolución de Liquidación\n",
        "    fecha_pago_transferencias DATE,       -- Fecha de pago de transferencias (a nivel central/FCE)\n",
        "    fecha_liquidacion_def DATE,           -- Fecha de Liquidación definitiva (cierre final)\n",
        "    obs_transferencias TEXT,              -- Observaciones sobre transferencias (comentarios finales)\n",
        "    fecha_envio       DATE,               -- Fecha de envío de documentación de liquidación\n",
        "    estado_liquidado_quipu  VARCHAR(50),  -- Estado liquidado en QUIPU (ej. 'Liquidado', 'Pendiente')\n",
        "    estado_liquidado_hermes VARCHAR(50),  -- Estado liquidado en HERMES\n",
        "    estado_contrato   VARCHAR(50),        -- Estado general del contrato (ej. 'Finalizado', 'Liquidado')\n",
        "    estado_rup        VARCHAR(50),        -- Estado RUP (Registro Único de Proveedores/contratos, si aplica)\n",
        "    gestion_documental VARCHAR(50),       -- Estado de gestión documental (ej. 'Completa', 'Pendiente')\n",
        "    FOREIGN KEY (id_cid) REFERENCES base_maestra(id_cid)\n",
        "        ON UPDATE CASCADE ON DELETE CASCADE\n",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n",
        "\n",
        "-- Tabla de Categorías de gasto en liquidación (normaliza las múltiples columnas de rubros de Liquidación).\n",
        "CREATE TABLE expense_category (\n",
        "    id_categoria   INT PRIMARY KEY AUTO_INCREMENT,\n",
        "    nombre_categoria VARCHAR(255) NOT NULL\n",
        "    -- (Ejemplos de categorías: 'Productos metálicos elaborados...', 'Impuestos', 'Servicios financieros', etc.)\n",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n",
        "\n",
        "-- Tabla de detalle de gastos por proyecto en cada categoría (Liquidación detallada).\n",
        "-- Cada registro representa el monto ejecutado en una categoría de gasto para el proyecto.\n",
        "CREATE TABLE liquidacion_gasto (\n",
        "    id_cid       INT NOT NULL,\n",
        "    id_categoria INT NOT NULL,\n",
        "    monto        DECIMAL(15,2) NOT NULL,\n",
        "    PRIMARY KEY (id_cid, id_categoria),\n",
        "    FOREIGN KEY (id_cid) REFERENCES base_maestra(id_cid)\n",
        "        ON DELETE CASCADE ON UPDATE CASCADE,\n",
        "    FOREIGN KEY (id_categoria) REFERENCES expense_category(id_categoria)\n",
        "        ON DELETE RESTRICT ON UPDATE CASCADE,\n",
        "    INDEX idx_gasto_categoria (id_categoria)\n",
        ") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;\n"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Ahora procedemos a la observación de vistas\n"
      ],
      "metadata": {
        "id": "CpTW55QpAG0w"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "-- Vista de proyectos en etapa de Propuestas: combina datos base + propuesta\n",
        "CREATE VIEW vw_propuestas AS\n",
        "SELECT\n",
        "    B.id_cid,\n",
        "    B.id_quipu,\n",
        "    B.id_hermes,\n",
        "    E.nombre_entidad AS entidad,\n",
        "    E.caracter_entidad AS caracter_entidad,\n",
        "    B.facultad_lider,\n",
        "    B.objeto,\n",
        "    B.saber_cid,\n",
        "    B.modalidad_extension,\n",
        "    P.tipologia AS tipologia_propuesta,\n",
        "    P.origen_proceso,\n",
        "    P.num_proceso,\n",
        "    P.modalidad_contratacion,\n",
        "    P.valor_cotizacion,\n",
        "    P.valor_contrato_marco AS valor_contrato_marco_estimado,\n",
        "    P.valor_contrato_otra_fac AS valor_contrato_otras_facultades,\n",
        "    P.valor_proyecto_fce AS valor_proyecto_estimado_FCE,\n",
        "    P.tiempo_ejecucion_estimado,\n",
        "    P.fecha_recepcion,\n",
        "    P.fecha_entrega,\n",
        "    B.estado_propuesta,\n",
        "    B.estado_firma,\n",
        "    P.id_autorizacion_dneipi,\n",
        "    P.fecha_presentacion_cf_prop,\n",
        "    P.acta_presentacion_cf_prop,\n",
        "    B.fecha_presentacion_cf_av,\n",
        "    B.acta_presentacion_cf_av,\n",
        "    B.id_acuerdo_voluntades,\n",
        "    B.fecha_firma_acuerdo_vol,\n",
        "    B.fecha_firma_contrato,\n",
        "    P.observaciones AS observaciones_propuesta\n",
        "FROM base_maestra B\n",
        "JOIN propuestas P ON B.id_cid = P.id_cid\n",
        "JOIN entidad E ON B.id_entidad = E.id_entidad;\n",
        "\n",
        "-- Vista de proyectos en etapa de Ejecución: combina datos base + ejecución\n",
        "CREATE VIEW vw_ejecucion AS\n",
        "SELECT\n",
        "    B.id_cid,\n",
        "    B.id_quipu,\n",
        "    B.id_hermes,\n",
        "    E.nombre_entidad AS entidad,\n",
        "    B.facultad_lider,\n",
        "    B.objeto,\n",
        "    B.modalidad_extension,\n",
        "    B.director,\n",
        "    B.tipo_vinculacion_director,\n",
        "    B.valor_contrato_fce,\n",
        "    B.presupuesto_comprometido,\n",
        "    B.porc_presupuesto_comprometido,\n",
        "    B.estado_ejecucion,\n",
        "    P.tipologia AS tipologia_propuesta,\n",
        "    X.tipo_proyecto,\n",
        "    X.vigencia_proyecto,\n",
        "    X.contrato,\n",
        "    X.valor_adicion,\n",
        "    B.valor_contrato_fce + IFNULL(X.valor_adicion,0) AS valor_proyecto_fce_total,  -- cálculo del valor final FCE (valor inicial + adición)\n",
        "    X.num_vinculacion,\n",
        "    B.fecha_inicio AS fecha_inicio_real,\n",
        "    X.fecha_inicio_ejecucion AS fecha_inicio_plan,\n",
        "    X.fecha_fin_ejecucion AS fecha_fin_plan,\n",
        "    B.fecha_finalizacion_pror AS fecha_fin_con_prorrogas,\n",
        "    X.fecha_fin_dir,\n",
        "    X.gestor,\n",
        "    X.responsable_ejecucion,\n",
        "    X.estado_pago_proy AS estado_pago_proyecto,\n",
        "    X.total_contratos,\n",
        "    X.contratos_pend_pago AS contratos_pendientes_pago,\n",
        "    X.valor_comprometido,\n",
        "    X.valor_pagado,\n",
        "    X.saldo_por_ejecutar,\n",
        "    X.obs_ejecucion AS observaciones_ejecucion\n",
        "FROM base_maestra B\n",
        "JOIN propuestas P ON B.id_cid = P.id_cid\n",
        "JOIN ejecucion X ON B.id_cid = X.id_cid\n",
        "JOIN entidad E ON B.id_entidad = E.id_entidad;\n",
        "\n",
        "-- Vista de proyectos en etapa de Liquidación: combina datos base + liquidación.\n",
        "CREATE VIEW vw_liquidacion AS\n",
        "SELECT\n",
        "    B.id_cid,\n",
        "    B.id_quipu,\n",
        "    B.id_hermes,\n",
        "    E.nombre_entidad AS entidad,\n",
        "    B.facultad_lider,\n",
        "    B.objeto,\n",
        "    B.modalidad_extension,\n",
        "    B.director,\n",
        "    L.contrato,\n",
        "    L.fecha_firma_contrato,\n",
        "    L.valor_contrato_total,\n",
        "    L.valor_ejecucion_fce,\n",
        "    B.valor_contrato_fce AS valor_contrato_fce_final,\n",
        "    B.valor_ejecutado,\n",
        "    B.excedentes,\n",
        "    L.fecha_inicio,\n",
        "    L.fecha_fin_ejecucion,\n",
        "    B.fecha_finalizacion_pror,\n",
        "    L.meses_ejecucion_pror,\n",
        "    B.fecha_liquidacion,\n",
        "    L.estado_liquidacion,\n",
        "    L.res_liquidacion_no,\n",
        "    L.fecha_liquidacion_def,\n",
        "    L.estado_liquidado_quipu,\n",
        "    L.estado_liquidado_hermes,\n",
        "    L.estado_contrato,\n",
        "    L.estado_rup,\n",
        "    L.gestion_documental,\n",
        "    L.obs_transferencias AS observaciones_liquidacion\n",
        "FROM base_maestra B\n",
        "JOIN liquidacion L ON B.id_cid = L.id_cid\n",
        "JOIN entidad E ON B.id_entidad = E.id_entidad;\n"
      ],
      "metadata": {
        "id": "Mm1aKjSIAN1D"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "DELIMITER $$\n",
        "\n",
        "-- Trigger: Antes de UPDATE en base_maestra – genera códigos cuando estado_firma cambia a 'Firmado'\n",
        "CREATE TRIGGER trg_base_before_update\n",
        "BEFORE UPDATE ON base_maestra\n",
        "FOR EACH ROW\n",
        "BEGIN\n",
        "    IF NEW.estado_firma = 'Firmado' AND (OLD.estado_firma <> 'Firmado' OR OLD.estado_firma IS NULL) THEN\n",
        "        -- Generar código QUIPU si no está asignado\n",
        "        IF NEW.id_quipu IS NULL OR NEW.id_quipu = '' THEN\n",
        "            SET NEW.id_quipu = CONCAT('QUIPU-', NEW.id_cid);\n",
        "        END IF;\n",
        "        -- Generar código HERMES si no está asignado\n",
        "        IF NEW.id_hermes IS NULL OR NEW.id_hermes = '' THEN\n",
        "            SET NEW.id_hermes = CONCAT('HERMES-', NEW.id_cid);\n",
        "        END IF;\n",
        "    END IF;\n",
        "END$$\n",
        "\n",
        "-- Trigger: Después de INSERT en base_maestra – genera códigos si un registro entra ya aprobado (Firmado)\n",
        "CREATE TRIGGER trg_base_after_insert\n",
        "AFTER INSERT ON base_maestra\n",
        "FOR EACH ROW\n",
        "BEGIN\n",
        "    IF NEW.estado_firma = 'Firmado' THEN\n",
        "        UPDATE base_maestra\n",
        "        SET id_quipu = CONCAT('QUIPU-', NEW.id_cid),\n",
        "            id_hermes = CONCAT('HERMES-', NEW.id_cid)\n",
        "        WHERE id_cid = NEW.id_cid;\n",
        "    END IF;\n",
        "END$$\n",
        "\n",
        "DELIMITER ;"
      ],
      "metadata": {
        "id": "-IwkjdCJAf1k"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "7_vgRlf-U68G"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [],
      "metadata": {
        "id": "oRGkQr5TXFeb"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "markdown",
      "source": [
        "ahora los triggers útiles\n"
      ],
      "metadata": {
        "id": "d4pJttDQAakm"
      }
    }
  ]
}